---
# General options
zabbix_version: "3.2"

# Zabbix_Agent_options
zabbix_agent_server:
zabbix_agent_serveractive:
zabbix_agent_hostname: "{{ ansible_fqdn }}"
zabbix_agent_pidfile: "/var/run/zabbix/zabbix_agentd.pid"
zabbix_agent_logfile: "/var/log/zabbix/zabbix_agentd.log"
zabbix_agent_logfilesize: 0
zabbix_agent_enableremotecommands: 1
# Zabbix_Api_options
zabbix_api_url: "10.10.10.30"
zabbix_api_user: "Admin"
zabbix_api_pass: "zabbix"
zabix_api_host_ip: 127.0.0.1