---

- name: Install MariaDB | Add repo_file
  apt_repository: repo="deb [arch=amd64,i386,ppc64el] http://mirror.timeweb.ru/mariadb/repo/{{ mariadb_version }}/debian jessie main" state=present
  register: mariadb_list

- name: Install MariaDB | Add apt_repo_key
  apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db
  register: mariadb_key

- name: Install MariaDB | Update apt-cache
  apt: update_cache=yes
  when: mariadb_list.changed == True or mariadb_key.changed == True

- name: Install MariaDB | Install MariaDB
  apt: pkg={{ item }} state=present
  with_items:
    - mariadb-server
    - mariadb-client

- name: Install MariaDB | Install MySQLdb Python package for secure installations.
  apt: pkg=python-mysqldb state=present
  when: mysql_secure_installation and mariadb_root_password is defined

- name: Install MariaDB | Deploy my.cnf
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf owner=root group=root mode=0600

- name: Install MariaDB | Start and enable service
  service: name=mysql state=started enabled=yes
  
- include: mysql_secure_installation.yml
  when: mysql_secure_installation and mariadb_root_password is defined

- include: zabbix_db.yml